#####
# Documentation
# YAML (all config values): https://render.com/docs/yaml-spec
#####

services:
  - name: marvel-api
    type: web
    env: node
    region: frankfurt
    buildCommand: yarn workspaces focus server
    startCommand: yarn workspace server start
    envVars:
      - key: NODE_VERSION
        value: 16
