name: Setup Database Server

on:
  push:
    branches:
      - main
    paths:
      - server/**

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn workspaces focus server

      - name: Migrate using Prisma Deploy
        run: cd server && yarn prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
  